### ISSUE TITLE
объединение аккаунтов - ???

### ISSUE THREAD

**Issue by ivangalin** [nvbn/djang0byte#10]
нажал в профиле ссылку, показалось окошко, сказали что придет письмо на почту - ничего не пришло

кроме обычного входа по паролю ничего не привязано

http://welinux.ru/user/GalS/

**Comment by nvbn** [comment]
Сегодня какие-то косяки, мне письмо шло где-то час.
Если сегодня не придёт, буду смотреть)

**Comment by VovanR** [comment]
Та же проблема. Прошло 17 минут. Письма нет.
Почта на гмыле. Галка "Показывать адрес электронной почты?" снята. Если это чем-то поможет.

**Comment by nvbn** [comment]
попробуйте сейчас

**Comment by VovanR** [comment]
Нет, всеравно не приходит. Даже сменил мыло на яндекс - не помогло.
И куки чистил, и с другого браузера заходил. С приватных вкладок все также.

**Comment by simakazi** [comment]
Подтверждаю этот баг. Мыло - ГМейл. Браузер - Хром.

**Comment by nvbn** [comment]
Профиксил =)
