### ISSUE TITLE
Не сохраняет правки при редактировании профиля

### ISSUE THREAD

**Issue by sakal** [nvbn/djang0byte#12]
На странице редактирования профиля (http://welinux.ru/action/edit_user/) выдаёт страницу с сообщение: "Что-то пошло не так, назад?"

**Comment by nvbn** [comment]
Регистрация нативная или через соц. сети?

**Comment by sakal** [comment]
Регистрация нативная.
Быть может это как-то связано: прежде кликал на "Объеденить аккаунты", но ничего не произошло.

**Comment by nvbn** [comment]
Не связано, сейчас посмотрю.

**Comment by nvbn** [comment]
Попробуйте сейчас войти на страницу редактирования и отправьте страницу с ошибкой на nvbn.rm@gmail.com

**Comment by sakal** [comment]
отправил

**Comment by nvbn** [comment]
сейчас нормально?

**Comment by sakal** [comment]
Нет, проблема осталась

**Comment by nvbn** [comment]
Так, а сейчас какая ошибка?

**Comment by sakal** [comment]
Та же самая, словно не было вмешательства
Отправил на почту сообщение об ошибке с traceback

**Comment by nvbn** [comment]
Сейчас явно должно заработать.

**Comment by sakal** [comment]
Работает :-)

**Comment by nvbn** [comment]
=)
