### ISSUE TITLE
Вместо комментов "Здесь был комментарий"

### ISSUE THREAD

**Issue by midler** [nvbn/djang0byte#2]
http://dl.dropbox.com/u/2378238/img/Screenshot%20at%202011-10-19%2023%3A00%3A15.png

Хром 14.0.835.202, Убунта 11.04

**Comment by nvbn** [comment]
Это как у тебя так?)

**Comment by midler** [comment]
ХЗ. Сам был вчера в шоке. "Я ничего не  трогал, оно само" (с)
Сейчас коменты нормально  отображаются, Тикет можно закрывать =)

**Comment by nvbn** [comment]
Окей =)
