### ISSUE TITLE
[косметика] лишний пробел в списке голосов

### ISSUE THREAD

**Issue by Philosoft** [nvbn/djang0byte#20]
Если у поста или комментария кликнуть на рейтинг, открывается список проголосовавших, между аватаркой и именем пользователя есть пробел, который подчёркивается, т.к. находится между тегом img и именем пользователя
<code>
div += '&lt;a href="/user/' + raters[i].username + '/"&gt;&lt;img class="mini_av" src="' + raters[i].avatar +'" /> '**_←лишний пробел тут**_ +
                    raters[i].username + '</a> поставил <span class="';

</code>

**Comment by dtantsur** [comment]
https://github.com/nvbn/djang0byte/pull/21
