### ISSUE TITLE
Во всех постах "здесь был комментарий" вместо комментариев.

### ISSUE THREAD

**Issue by uscr** [nvbn/djang0byte#29]
Во всех, кроме постов из талкса. Браузер - Chrome 20.0.1132.57

**Comment by nvbn** [comment]
Залогинены?
И можно скрин?

**Comment by uscr** [comment]
Залогинен. При разлогине ничего не меняется. На огнелисе всё хорошо. Скрин чего нужен? Кусочка с комментариями вот: http://uscr.ru/share/fail.jpg

В коде страницы комментарий виден и выглядит так:

<div class='comment' id="cmnt117640" style="margin-left:0px;">
    <div class='comment_top'>
        <a href="/user/mealsforall/" class="comment_author"><img src='/media/style/figure.gif' class='mini_av' />mealsforall</a>
        <span class="date">24.07.2012 18:22</span>
        <a href="/post/7270/#cmnt117640">#</a>
        
        <div class="comment_rate" title="Количество голосов: 0">
            <a class="plus_rate" href='/action/ratecom/117640/1/'>+</a>
                <a href="#/comment/117640/"
                
                    class='rate_val raters'
                
                >
                    0
                </a>
            <a class="minus_rate" href='/action/ratecom/117640/0/'>-</a>
        </div>
    </div>
    <div class="comment_text">
        
            Отлично! А кто "мы"?
        
    </div>
<div class='comment_bottom'>

    <a class='comment_reply' href='/newcomment/7270/117640/'><img src="/media/style/speech_bubble.gif" alt="" />Ответить</a>




</div>

**Comment by uscr** [comment]
Блин... Код выглядит так:

http://pastebin.com/wZ4p09Ha

**Comment by nvbn** [comment]
Может какое-нибудь дополнение мешает.
А если попробовать в "режиме инкогнито"?

**Comment by uscr** [comment]
ЫЫЫ! Мешал "WelinuxRating".

**Comment by nvbn** [comment]
Фух, не пришлось с телефона править код =)
