### ISSUE TITLE
[fr] Удобства для анонимов

### ISSUE THREAD

**Issue by Philosoft** [nvbn/djang0byte#31]
Предлагаю на основе куков для незарегеных пользователей сделать удобные плюшки:
- Выделение цветом новых комментариев;
- панелька справа для проверки новых комментариев, как у зарегестрированных пользователей

_P.S._ Да, я всё ещё надеюсь на удовлетворение фичреквестов и исправление багов. Слабо правда.

**Comment by nvbn** [comment]
Как-нибудь засяду и добью рефакторинг с багфиксами и фичреквестами =)

**Comment by Philosoft** [comment]
irrelevant. dead/abandoned project.
