### ISSUE TITLE
Проблемы при разворачивании сего творения

### ISSUE THREAD

**Issue by amaaov** [nvbn/djang0byte#34]
При клонировании с github не оказалось файлика deps.
Далее потребовалось ставить ещё ряд пакетов: jsonrpc, lxml, simplejson, django-mptt
И это ещё только запуск deploy.py

Помимо этого main.models пытается импортировать из неких djang0parser и baseutils, которых и в помине нет.

Более того, import mptt срабатывает без ошибок, но при работе deploy.py вылезает ImportError: cannot import name MPTTModel

Такие дела.

**Comment by nvbn** [comment]
Инструкция старая, сейчас нужно просто всё из requirements.txt ставить и прогонять тесты)
