### ISSUE TITLE
Опечатка в main.css

### ISSUE THREAD

**Issue by VovanR** [nvbn/djang0byte#4]
djang0byte/media/style/main.css
Строка 109

https://github.com/nvbn/djang0byte/blob/master/djang0byte/media/style/main.css#L109

Вместо:
a.plust_rate, a.minus_rate {

Должно быть:
a.plus_rate, a.minus_rate {

**Comment by VovanR** [comment]
Закоммитил [master 1d34856]

**Comment by nvbn** [comment]
Куда?
На выходных обновлю сервер =)

**Comment by VovanR** [comment]
В ветку master
commit "1d348564c3b3b7ce6d6154aed259b54a245c42b2"
С комментарием Fix rate plus button
