### ISSUE TITLE
Не приходят уведомления на e-mail

### ISSUE THREAD

**Issue by uscr** [nvbn/djang0byte#7]
В профиле указан верный e-mail, проставлены все галочки касаемо уведомлений, но ни одного уведомления мне никогда не приходило.
Кстати, при регистрации мне тоже не пришло письмо для активации - активировал аккаунт через общение по e-mail с одним из разработчиков.

Ник на сайте: uscr

**Comment by uscr** [comment]
https://github.com/nvbn/djang0byte/issues/1 -- вот похожий баг, кстати.

**Comment by nvbn** [comment]
Профиксил =)
